In [1]:
import numpy as np


In [2]:
# How to generate 1-D Array
#shift+tab
array_a = np.array([1,2,3,4])

In [3]:
array_a

array([1, 2, 3, 4])

In [4]:
#How to create 2-D array : We need double square bracket on the outside
array_b = np.array([[1,2,3,4],[5,6,7,8]])


In [5]:
array_b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

type(arra_a)

In [6]:
type(array_a)

numpy.ndarray

In [7]:
array_a.shape

(4,)

In [ ]:
## The shape of the array_a is 4. or We have one dimentional array of size 4

In [8]:
array_b.shape

(2, 4)

In [9]:
# (2,4) means two rows and three columns

In [10]:
# To find the number of rows
array_b.shape[0]

2

In [11]:
# To find the number of columns
array_b.shape[1]

4

In [12]:
array_c =np.array(13)

In [13]:
type(array_c)

numpy.ndarray

In [14]:
array_c.shape  # No length or shape

()

In [15]:
array_d = np.array([15])

In [16]:
type(array_d)

numpy.ndarray

In [17]:
array_d.shape

(1,)

In [18]:
array_e=np.array([[15]]) # This is two diemntional array

In [19]:
array_e

array([[15]])

In [ ]:
## The number of opening and closing brackets an array has indicates how many dimensions it requires.