In [7]:
import numpy as np


In [1]:
list_a =[1,2,3,4,5,6]

In [2]:
len(list_a)

6

In [3]:
list_b =[[1,2,3,4],[2,4,5,6]] # A list of lists

In [4]:
len(list_b)

2

In [5]:
# we can jusr plug in list as inputs of the np.array() function

In [13]:
array_b =np.array(list_b)

In [14]:
type(list_b)

list

In [15]:
type(array_b)

numpy.ndarray

In [17]:
print(list_b)

[[1, 2, 3, 4], [2, 4, 5, 6]]


In [16]:
print(array_b)

[[1 2 3 4]
 [2 4 5 6]]


In [18]:
array_b.shape

(2, 4)

In [19]:
#list_b.shape  # list don't have shape
len(list_b) # determine how many sublist insode the  list

2

In [20]:
# Array operation works elemnet wise while list operation don't

In [21]:
list_c = list_b[0] + list_b[1]
array_c = array_b[0] + array_b[1]

In [22]:
print(list_c) # it just concanetate first sublist with the second sublist

[1, 2, 3, 4, 2, 4, 5, 6]


In [23]:
print(array_c) # It did the element wise addition

[ 3  6  8 10]


In [24]:
# To find the square route
np.sqrt(array_a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])