In [1]:
import numpy as np

Indexing

In [3]:
# Indices(or Indexes): We use indices to refer to the individual elements within an array
# Coordinates that heplp us navigate through the array
# in array index number refer to row number where index number is for each element
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

Specific values

In [4]:
# if we want an individual element of an array we need to provide an index for each dimension of the variable
array_a[0]

array([1, 2, 3])

In [5]:
array_a[1]

array([4, 5, 6])

In [6]:
# if we want to find the second element of first row : row index 0, index for second element in that row is 1
array_a[0][1]

2

In [7]:
# if we want to find the first  element of second row
array_a[1][0]

4

In [8]:
## other way
array_a[1,0]

4

In [9]:
## This tells python to go through all the rows from this column
array_a[:,0]

array([1, 4])

NEGATIVE INDICES

In [10]:
# Traversing the array backwards
array_b = np.array([1,2,3])
array_b[-1]

3

In [12]:
array_a[-1,-1]

6