In [3]:
import numpy as np

ASSIGNING VALUES

In [2]:
array_a =np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
## Changing the value of 3rd element in first row(3)
array_a[0,2]=9
array_a

array([[1, 2, 9],
       [4, 5, 6]])

In [4]:
# We can also change entire vectors within an array
array_a[0]=9
array_a

array([[9, 9, 9],
       [4, 5, 6]])

In [6]:
array_a[:,0]=9
array_a

array([[9, 9, 9],
       [9, 5, 6]])

In [7]:
# if we want to assign diffrent values in diffrent position
list_a =[8,7,8]
array_a[0] =list_a  # first row of the array is equal to list_a

In [8]:
array_a

array([[8, 7, 8],
       [9, 5, 6]])

In [9]:
type(array_a[0])

numpy.ndarray

In [10]:
# change the entire array with a single value
array_a[:]=9

In [11]:
array_a

array([[9, 9, 9],
       [9, 9, 9]])

ELEMENT WISE PROPERTIES

Whatever mathematetical computation we are conducting we are doing it to each element of the array.
The main purpose of an array is to perform coputational operation

In [16]:
array_a1=np.array([7,8,9])
array_a1

array([7, 8, 9])

In [13]:
array_b=np.array([[1,2,3],[4,5,6]])
array_b


array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
array_a1 + 4


array([11, 12, 13])

In [19]:
array_a1

array([7, 8, 9])

In [20]:
array_a1 + 2

array([ 9, 10, 11])

In [22]:
array_b+2

array([[3, 4, 5],
       [6, 7, 8]])

In [23]:
#In case of list it will concanetate

list_a = [1,2,3]

In [25]:
list_a + [2]

[1, 2, 3, 2]

In [28]:
# Two diffrent array
# each individual element is added up with it's corresponding counterpart from the other array/elementwise addition
# The shape of the array must be compatible. The lenght of the 1-D array must match the "length" of the 2-D array.
# The order in which we write array is important

array_a + array_b[0]

array([ 8, 10, 12])

In [29]:
array_a

array([7, 8, 9])

In [30]:
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
array_a + array_b[1] # 2nd row

array([11, 13, 15])

In [33]:
array_a -array_b[0]

array([6, 6, 6])

In [34]:
array_a - array_b[1]

array([3, 3, 3])

In [35]:
array_a * array_b[0]

array([ 7, 16, 27])

In [36]:
array_a *array_b[1]

array([28, 40, 54])

In [37]:
array_a / array_b[0]

array([7., 4., 3.])

DataTypes Supported by Numpy

In [1]:
# Arrays can contain number. All the numerical datatypes supported by C
# We can specify the the type of our dataset using dtype
#Two ways to declare data type  dtype="data_type/float16" or dtype=np.data_type/float16

In [4]:
array_a =np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
array_a =np.array([[1,2,3],[4,5,6]], dtype=np.float16)
array_a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)

In [8]:
# With complex number
array_a =np.array([[1,2,3],[4,5,6]], dtype=np.complex64)
array_a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [9]:
narray_a =np.array([[1,2,3],[4,5,6]], dtype=np.bool)
array_a

C:\Users\13612\AppData\Local\Temp\ipykernel_17056\1833267392.py:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  narray_a =np.array([[1,2,3],[4,5,6]], dtype=np.bool)


array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [10]:
array_a =np.array([[1,2,3],[4,5,6]], dtype=np.str)
array_a

C:\Users\13612\AppData\Local\Temp\ipykernel_17056\1163112924.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  array_a =np.array([[1,2,3],[4,5,6]], dtype=np.str)


array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U1')