Charecteristic of Numpy Functions

In [1]:
# Universal Functions: Work with NDarrays on an element-by-element bases

In [2]:
import numpy as np

In [3]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

In [5]:
array_b= np.array([[1],[2]])
array_b

array([[1],
       [2]])

In [6]:
matrix_c=np.array([[1,2,3],[4,5,6]])
matrix_c


array([[1, 2, 3],
       [4, 5, 6]])

BROADCASTING

In [8]:
# np.add() function to add to array

np.add(array_a,matrix_c)

array([[2, 4, 6],
       [5, 7, 9]])

In [9]:
np.add(array_b,matrix_c)

array([[2, 3, 4],
       [6, 7, 8]])

TYPE CASTING

In [10]:
np.add(array_a,matrix_c, dtype=np.float64)

array([[2., 4., 6.],
       [5., 7., 9.]])

Running Over an axis

In [11]:
np.mean(matrix_c, axis=0)

array([2.5, 3.5, 4.5])

In [12]:
matrix_c

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
np.mean(matrix_c, axis=1)

array([2., 5.])