Basic Slicing

In [1]:
import numpy as np

In [2]:
matrix_A = np.array([[1,2,3],[4,5,6]])
matrix_A

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
matrix_A[0:1]    # Here 0 and 1 are now index 0 index is first row and before 1 index is 0 which is also first row

array([[1, 2, 3]])

In [5]:
matrix_A[:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
matrix_A[:1] # Give all rows before index 1 rows

array([[1, 2, 3]])

In [7]:
matrix_A[1:] # Slicing will start with the  row with index 1 and give all the rows after that

array([[4, 5, 6]])

In [8]:
matrix_A[2:] # we don't have third row , O-dimension output

array([], shape=(0, 3), dtype=int32)

In [9]:
matrix_A[:2] # Slicing all the rows prior to the index 2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
# Indexing is very similar to slicing
#indexing =specific indexing
# slicing = interval indexing
# The numerical values are identical but the output vary in dimensions

In [11]:
matrix_A[0]

array([1, 2, 3])

In [12]:
matrix_A[:1]

array([[1, 2, 3]])

In [13]:
matrix_A[:-1] # comprises all the rows but not include the last one

array([[1, 2, 3]])

In [14]:
# slicing column

In [15]:
matrix_A[:,1:]  # It will give all the rows and the column starting from the one with index one

array([[2, 3],
       [5, 6]])

In [16]:
matrix_A

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
matrix_A[1:,1:] 

array([[5, 6]])

# Stepwise slicing

In [18]:
matrix_B =np.array([[1,1,1,2,0],[3,6,6,7,4],[4,5,3,8,0]])
matrix_B

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [19]:
matrix_B[:,:] # entire dataset

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [21]:
matrix_B[::2,::]  # started with the row with index 0 and jump to the row with index 2/we are slicing every other row

array([[1, 1, 1, 2, 0],
       [4, 5, 3, 8, 0]])

In [22]:
matrix_B[::,::2]  # started with the column with index 0 and jump to the column with index 2/we are slicing every other column

array([[1, 1, 0],
       [3, 6, 4],
       [4, 3, 0]])

In [23]:
matrix_B[::2,::2] # Every other value of every other row, starting from the first// Every second value of the row

array([[1, 1, 0],
       [4, 3, 0]])

In [24]:
matrix_B[-1::-2,::2] 

array([[4, 3, 0],
       [1, 1, 0]])

In [25]:
matrix_B[-1::-1,::2] 

array([[4, 3, 0],
       [3, 6, 4],
       [1, 1, 0]])

## CONDITIONAL SLICING

In [26]:
matrix_c = np.array([[1,1,1,2,0],[3,6,6,7,4],[4,5,3,8,0]])
matrix_c

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [28]:
matrix_c[:,0]

array([1, 3, 4])

In [29]:
matrix_c[:,0]>2

array([False,  True,  True])

In [30]:
matrix_c[:,:]>2

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

=>what if we want to know the exact values which satisfies the consition?
=>we need to write the conditional part as an index within the square bracket Reason why the output is a 1-D array:
=>1. Numpy does not know how many of the elements would fit this condition
=>2. Python takes the flattened array(which is 1-D) and applies the condition on it
=>Multiple conditions: & ="and" || = OR 
=> Conditional slicing is a fantasti tool to filter out certain data
=> Helps us slice only the parts of the array we are interested in

In [32]:
matrix_c[matrix_c[:,:]>2]

array([3, 6, 6, 7, 4, 4, 5, 3, 8])

In [33]:
matrix_c[(matrix_c[:,:]%2==0) &(matrix_c[:,:]<=4) ] # Even number < or = to 4

array([2, 0, 4, 4, 0])

## Dimension and  Squeze Function

In [34]:
matrix_D =np.array([[1,1,1,2,0],[3,6,6,7,4],[4,5,3,8,0]])
matrix_D

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [36]:
type(matrix_D[0,0])

numpy.int32

In [37]:
print(matrix_D[0,0])

1


In [38]:
type(matrix_D[0,0:1]) # only include the first element of the first column of the row

numpy.ndarray

In [39]:
print(matrix_D[0,0:1]) # 1-d array

[1]


In [40]:
type(matrix_D[0:1,0:1])

numpy.ndarray

In [41]:
print(matrix_D[0:1,0:1]) # 2-d array

[[1]]


In [42]:
print(matrix_D[0,0].shape)
print(matrix_D[0,0:1].shape)
print(matrix_D[0:1,0:1].shape)

()
(1,)
(1, 1)


In [43]:
# What difference does it make whether we're storing it as a scaler, vector or matrix?
# Certain function or methods can only be executed with inputs of a fixed size.
# So its important to be consistent when working with arrays
# the squeze method removes all the unnecessary dimensions of an array
# when we squeeze an array(holding a single value) along all its axes, we get a single numeric value
# As long as we apply the squeeze method or function we can use any slicing variation to get the same chunk of data

In [44]:
matrix_D[0:1,0:1].squeeze() # This output is a 0-D array rather than a scalar

array(1)

In [45]:
type(matrix_D[0:1,0:1].squeeze())

numpy.ndarray

In [46]:
matrix_D[0:1,0:1].squeeze().shape

()

In [47]:
print(matrix_D[0:1,0:1].squeeze()) # The value that will be actually used in further calculations

1


In [48]:
# Equivalent function
np.squeeze(matrix_D[0:1,0:1])

array(1)

In [49]:
print(matrix_D[0,0].squeeze().shape)   # shape is an attribute rather than a method
print(matrix_D[0,0:1].squeeze().shape)
print(matrix_D[0:1,0:1].squeeze().shape)

()
()
()
