In [1]:
import numpy as np

In [2]:
array_empty =np.empty(shape=(2,3))
array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
array_zeros =np.zeros(shape=(2,3), dtype=np.int8)
array_zeros

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [5]:
array_ones =np.ones(shape=(2,3), dtype=np.int8)
array_ones

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [7]:
array_full = np.full(shape=(2,3), fill_value=2)
array_full

array([[2, 2, 2],
       [2, 2, 2]])

In [8]:
array_full = np.full(shape=(2,3), fill_value="Text")
array_full

array([['Text', 'Text', 'Text'],
       ['Text', 'Text', 'Text']], dtype='<U4')

### _like Function


In [9]:
matrix_A = np.array([[1,2,3,4,5],[6,3,4,5,5],[0,3,2,4,6]])
matrix_A

array([[1, 2, 3, 4, 5],
       [6, 3, 4, 5, 5],
       [0, 3, 2, 4, 6]])

In [11]:
array_empty_like = np.empty_like(matrix_A) # empty funtion does not provide consistent output
array_empty_like

array([[4128860, 6029375, 3801155, 5570652, 6619251],
       [7536754, 3211356, 3538995, 3276849, 4259932],
       [7340144, 6357060, 6357108, 4980828, 6488175]])

In [12]:
array_zeros_like = np.zeros_like(matrix_A) # empty funtion does not provide consistent output
array_zeros_like

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## np.arange()

In [13]:
range(30)

range(0, 30)

In [15]:
list(range(5))

[0, 1, 2, 3, 4]

In [19]:
array_rng = np.arange(start=0 ,stop=30) # it include the lower bound but not the upper one 
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [22]:
array_rng = np.arange(start=0 ,stop=30, step=3, dtype=np.float64) # it include the lower bound but not the upper one 
array_rng

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [24]:
array_rng = np.arange(start=0 ,stop=30, step=2.5, dtype=np.int32) # it include the lower bound but not the upper one 
array_rng

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

## Random Generator and Seeds

In [25]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [27]:
array_RG = gen(pcg())
array_RG.normal(size=(5,5))  # Clarification: The shape of the array will be equal to the tuple(5,5) in this case

array([[-0.45482968, -1.63545462,  1.19571105,  0.28447506, -0.91130021],
       [-0.0931147 ,  1.23464657,  1.36727685, -0.05818258, -0.29249835],
       [-0.93280375, -1.67090547, -0.59582813,  0.06101153,  0.81672593],
       [ 0.38323549,  1.2598384 , -1.84914361, -1.44609967, -0.48366127],
       [ 0.24510074,  0.46771873, -1.83939341,  0.0902766 , -0.53701846]])

In [28]:
array_RG = gen(pcg(seed=365))
array_RG.normal(size=(5,5))

array([[-0.13640899,  0.09414431, -0.06300442,  1.05391641, -0.6866818 ],
       [-0.50922173, -0.7999526 ,  0.73041825,  0.08825439, -2.1177576 ],
       [ 0.65526774, -0.48095012, -0.5519114 , -0.58578662, -0.98257896],
       [ 1.12378166, -1.30984316, -0.04703774,  0.955272  ,  0.26071745],
       [-0.20023668, -1.50172484, -1.4929163 ,  0.96535084,  1.18694633]])

In [29]:
# A seed only last for one execution of a method or function before it is reset
# Hence Whenever we intend to use a seed , we'll have to reset it every time
array_RG.normal(size=(5,5))

array([[-0.76065577,  1.48158358,  0.01200258, -0.06846959,  0.25301664],
       [-0.52640788,  0.79613109,  0.28203421,  1.80238008,  0.93932117],
       [-0.53693283, -0.26317689, -1.77723035,  1.14900013, -2.20733915],
       [ 1.54116775, -0.5124932 , -2.14564563,  1.98878673,  0.32208907],
       [-1.2651495 ,  3.2714633 ,  1.78650493, -0.20233675,  0.20427467]])

In [30]:
array_RG.normal(size=(5,5))

array([[ 0.58830139,  0.43063835,  0.42871861, -0.49041682,  0.58326844],
       [-0.10015833, -1.27535497,  0.94226986,  0.01434193, -1.20783944],
       [ 0.16767707, -1.35242456,  0.51855231,  0.66726422,  0.5453976 ],
       [-0.46037542,  2.10611129,  0.79579772, -1.44055324, -0.62070809],
       [ 2.16041849, -0.50664074,  0.08321514,  0.87416817,  1.98530199]])

## Random Integers, Probabilities and Choices

In [32]:
# numpy.integers()
array_RG = gen(pcg(seed=365))
array_RG.integers(low=10, high =100, size =(5,5))

array([[18, 78, 64, 78, 84],
       [66, 67, 28, 10, 69],
       [45, 15, 37, 74, 96],
       [19, 21, 89, 73, 54],
       [53, 84, 66, 51, 92]], dtype=int64)

In [33]:
#numpy.random()
array_RG = gen(pcg(seed=365))  # probability stay between 0 to 1
array_RG.random(size =(5,5)) 

array([[0.75915734, 0.7662218 , 0.6291028 , 0.20336599, 0.66501486],
       [0.06559111, 0.71326309, 0.10812106, 0.87969046, 0.49405844],
       [0.82472673, 0.45652944, 0.07367232, 0.69628564, 0.36690736],
       [0.29787156, 0.4996155 , 0.4865245 , 0.62740703, 0.54952637],
       [0.64894629, 0.04411757, 0.7206516 , 0.84594003, 0.17159792]])

In [34]:
#numpy.choices()
# Stimulates the idea of making an arbitrary  choice out of a given sequence
# We can manually set the probability for each argument of the method


In [37]:
array_RG = gen(pcg(seed=365))  # probability stay between 0 to 1
array_RG.choice([1,2,3,4,5],p=[0.2,0.2,0.2,0.3,0.1],size =(5,5)) 

array([[4, 4, 4, 2, 4],
       [1, 4, 1, 4, 3],
       [4, 3, 1, 4, 2],
       [2, 3, 3, 4, 3],
       [4, 1, 4, 4, 1]])

## Random Probability Distribution

#### Generating Arrays From known distribution

In [38]:
array_RG = gen(pcg(seed=365))  


In [40]:
## Poisson Distribution 
# Default value for lamda is 1 This means over a fixed interval of time distance or space,
#we expect an event to occur exacly once
array_RG.poisson(size =(5,5))

array([[1, 0, 2, 4, 0],
       [0, 0, 0, 0, 1],
       [2, 3, 1, 1, 0],
       [1, 0, 4, 1, 2],
       [2, 2, 0, 0, 1]], dtype=int64)

In [41]:
array_RG.poisson(lam=10,size =(5,5))

array([[15, 11,  9,  6, 14],
       [10, 16, 12,  9,  4],
       [ 9,  6, 10,  9,  7],
       [ 9, 18, 11, 11,  4],
       [11,  6,  8,  4,  7]], dtype=int64)

In [42]:
## Binomial Distribution
#Measures how many times a certain outcome can appear over a series of trials, where there are only 2 possible outcomes

In [45]:
array_RG = gen(pcg(seed=365))     # on average most of the outcomes are around 40 
#//40 % probability of getting what we want on each of the 100 individual trials
array_RG.binomial(n=100, p=0.4 ,size =(5,5))

array([[42, 44, 30, 36, 45],
       [36, 41, 38, 42, 41],
       [35, 31, 35, 46, 29],
       [41, 41, 46, 34, 48],
       [45, 45, 45, 40, 43]], dtype=int64)

In [46]:
## Logistic Distribution
array_RG = gen(pcg(seed=365))
array_RG.logistic(loc=9, scale=1.2 ,size =(5,5))

array([[10.37767822, 10.42451863,  9.63404367,  7.36153427,  9.82286787],
       [ 5.81223125, 10.09354231,  6.46790532, 11.38740256,  8.97147918],
       [10.85844698,  8.79081317,  5.962079  ,  9.99560681,  8.34539118],
       [ 7.97105522,  8.9981544 ,  8.93530194,  9.6253307 ,  9.23850869],
       [ 9.73729284,  5.3090678 , 10.13723528, 11.04372782,  7.11078651]])

## Application of random Generator

In [47]:
array_column_1 = array_RG.normal(loc=2, scale=3 ,size =(1000))
array_column_2 = array_RG.normal(loc=7, scale=3 ,size =(1000))
array_column_3 = array_RG.logistic(loc=11, scale=3 ,size =(1000))
array_column_4 = array_RG.exponential(scale=4 ,size =(1000))
array_column_5 = array_RG.geometric(p=0.7,size =(1000))

In [51]:
random_test_data =np.array([array_column_1,array_column_2,array_column_3,array_column_4,array_column_5]).transpose()
random_test_data

array([[ 5.560839  ,  4.59454548,  6.64872801,  4.09900697,  1.        ],
       [-0.28196732,  7.05082384, 14.07400141,  5.7882515 ,  1.        ],
       [ 6.44475073,  7.4344136 , 14.09121743,  2.20135186,  1.        ],
       ...,
       [ 1.04822206,  5.58282466, 14.96507816,  7.07574646,  1.        ],
       [ 2.13294147,  4.78671485,  8.84971156,  5.52128051,  2.        ],
       [ 1.57375454,  8.96572808,  7.93037608,  6.02450182,  1.        ]])

In [49]:
random_test_data.shape

(5, 1000)

In [50]:
# Transposing a matrix : transforming rows into columns and (vice versa)

In [52]:
np.savetxt('Random_Test_from.Numpy.csv', random_test_data,fmt="%s", delimiter=',')

In [53]:
#we can import the newly created csv back into python and display its contents

In [54]:
np.genfromtxt("Random_Test_from.Numpy.csv",delimiter=',' )

array([[ 5.560839  ,  4.59454548,  6.64872801,  4.09900697,  1.        ],
       [-0.28196732,  7.05082384, 14.07400141,  5.7882515 ,  1.        ],
       [ 6.44475073,  7.4344136 , 14.09121743,  2.20135186,  1.        ],
       ...,
       [ 1.04822206,  5.58282466, 14.96507816,  7.07574646,  1.        ],
       [ 2.13294147,  4.78671485,  8.84971156,  5.52128051,  2.        ],
       [ 1.57375454,  8.96572808,  7.93037608,  6.02450182,  1.        ]])