## Statistics With Numpy

In [1]:
import numpy as np

In [4]:
matrix_A = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [6]:
# The mean value for the flattened array. Ignoring the shape of the array and flattening it down to a long 1-dimensional array
#[1,0,0,3,1,3,6,6,2,9,4,5,3,8,0] mean =Addition of all elements/ total number of elements
np.mean(matrix_A) 

3.4

In [7]:
#To find the mean only for the data in  first row
np.mean(matrix_A[0])

1.0

In [8]:
# An integer is displayed as a decimal because the default datatype for the output of np.mean() is actually float64

In [10]:
#To find the mean only for the data in  first column
np.mean(matrix_A[:,0])

2.6666666666666665

In [11]:
#To find the mean  for the data in  all column separately
np.mean(matrix_A, axis =0)

array([2.66666667, 3.66666667, 3.        , 4.33333333, 3.33333333])

In [12]:
#To find the mean  for the data in  all row separately
np.mean(matrix_A, axis =1)

array([1. , 5.2, 4. ])

In [13]:
np.mean(matrix_A, axis =0, dtype=np.int64)

array([2, 3, 3, 4, 3], dtype=int64)

### Minimal and Maximal Values 

In [14]:
matrix_A = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [15]:
np.min(matrix_A)

0

In [16]:
np.min(matrix_A[1])# second row

2

In [17]:
np.min(matrix_A[:,1]) # second column

0

In [18]:
#np.amin() a --> array. this function is specifically design for working with arrays
#np.min and np.amin produce the same results. So how exactly are these two function diffrent?
#They are absoluteltly equivalnet and interchangable. So either one is a matter of personal preference


In [19]:
np.amin(matrix_A)

0

In [21]:
np.minimum(matrix_A[0],matrix_A[2]) # only took the minima value from each row

array([1, 0, 0, 3, 0])

In [22]:
# If we reduce the inputs of a matrix, we can essentially pass all of its rows as inputs simultaneously

In [23]:
np.minimum.reduce(matrix_A) # The result chhose minimal value from each column of the matrix

array([1, 0, 0, 2, 0])

In [25]:
# same as using mean over the 0 axis
np.min(matrix_A, axis=0)

array([1, 0, 0, 2, 0])

In [26]:
# So two exprssions are equivalent(result in the same output). We can use any of them

In [27]:
#np.max() and np.amax works the exact same way as min
np.max(matrix_A)

9

In [28]:
np.amax(matrix_A)

9

In [29]:
np.maximum.reduce(matrix_A)

array([4, 6, 6, 8, 9])

### Statistical Order Function
#### Percentiles and Quantiles

In [30]:
import numpy as np

In [31]:
matrix_A = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [32]:
np.ptp(matrix_A) # highest =9 , lowest =0 , diffrence =9

9

In [33]:
np.ptp(matrix_A, axis=0)4-1, 6-0, 6-0,8-2,9-0 (column -higest and lowest value)

array([3, 6, 6, 6, 9])

In [35]:
np.ptp(matrix_A, axis=1) # 3-0, 9-2, 8-0 (row -higest and lowest value)

array([3, 7, 8])

In [37]:
np.sort(matrix_A, axis=None)

array([0, 0, 0, 1, 1, 2, 3, 3, 3, 4, 5, 6, 6, 8, 9])

In [39]:
np.percentile(matrix_A,70, interpolation="midpoint") # linear interpolation ,interpolation=midpoint/higher/lower/nearest

4.5

In [40]:
np.percentile(matrix_A,50) # we will get the median of the set, median = middle value of the sorted dataset

3.0

In [41]:
np.quantile(matrix_A,0.70, interpolation="nearest")

4.799999999999999

### Average and variance

In [42]:
import numpy as np

In [43]:
matrix_A = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [44]:
np.median(matrix_A)

3.0

In [45]:
np.sort(matrix_A, axis=None)

array([0, 0, 0, 1, 1, 2, 3, 3, 3, 4, 5, 6, 6, 8, 9])

In [46]:
np.mean(matrix_A)

3.4

In [47]:
#np,average() Compute the average of an array
np.average(matrix_A)

3.4

In [48]:
## Create an array with random generator
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

array_RG = gen(pcg(365))
array_weights = array_RG.random(size=(3,5))
array_weights


array([[0.75915734, 0.7662218 , 0.6291028 , 0.20336599, 0.66501486],
       [0.06559111, 0.71326309, 0.10812106, 0.87969046, 0.49405844],
       [0.82472673, 0.45652944, 0.07367232, 0.69628564, 0.36690736]])

In [49]:
np.average(matrix_A, weights=array_weights)

3.2120290871899306

In [50]:
np.var(matrix_A)

7.84

In [51]:
np.std(matrix_A)

2.8

### Covariance and Correlation

In [52]:
import numpy as np

In [53]:
matrix_A = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [59]:
np.cov(matrix_A)

array([[ 1.5, -2. ,  2. ],
       [-2. ,  7.7, -7. ],
       [ 2. , -7. ,  8.5]])

In [60]:
np.corrcoef(matrix_A)

array([[ 1.        , -0.58848989,  0.56011203],
       [-0.58848989,  1.        , -0.8652532 ],
       [ 0.56011203, -0.8652532 ,  1.        ]])